
GET http://localhost:9000/admin/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY3Rvcl9pZCI6InVzZXJfMDFKU1cxTlNSUlY0OEM2VDJDQ1g4UVpQUVAiLCJhY3Rvcl90eXBlIjoidXNlciIsImF1dGhfaWRlbnRpdHlfaWQiOiJhdXRoaWRfMDFKU1cxTlNXNFNBNDc5UVNTUVNZUko5NVIiLCJhcHBfbWV0YWRhdGEiOnsidXNlcl9pZCI6InVzZXJfMDFKU1cxTlNSUlY0OEM2VDJDQ1g4UVpQUVAifSwiaWF0IjoxNzQ1NzcyMDIyLCJleHAiOjE3NDU4NTg0MjJ9.AJ8v0rreBzwrwoMoLYrG7vT867C_Yhe7DSJPT-Q7DN0
